# Generated by Django 5.1.1 on 2026-10-04 06:55

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^(?!me\\Z)[\\w.@+-]+\\Z', 2), code='invalid_username', message='Username: допускаются буквы, цифры и символы @/./+/-/_ ; имя "me" зарезервировано и запрещено.')], verbose_name='имя пользователя'),
        ),
    ]
