# Generated by Django 5.1.1 on 2026-10-08 19:20

import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(db_index=True, validators=[reviews.models.validate_year], verbose_name='Год выпуска'),
        ),
    ]
